# Generated by Django 5.2.7 on 2025-10-17 06:40

import django.db.models.deletion
import item.choices
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarBody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тип кузова',
                'verbose_name_plural': 'Тип кузова',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='CarMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Марка',
                'verbose_name_plural': 'Марка',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Модель',
                'verbose_name_plural': 'Модель',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='FuelType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тип топлива',
                'verbose_name_plural': 'Тип топлива',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(choices=item.choices.year_choices, verbose_name='Год')),
                ('horse_power', models.PositiveSmallIntegerField(choices=item.choices.horse_power_choice, verbose_name='ХЫПЫ')),
                ('seat', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='кл-во сидений')),
                ('mileage', models.PositiveIntegerField(verbose_name='Пробег')),
                ('preview_img', models.ImageField(blank=True, null=True, upload_to='cars/', verbose_name='Превью фото')),
                ('body', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.carbody', verbose_name='Тип кузова')),
                ('mark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.carmark', verbose_name='Марка')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.carmodel', verbose_name='Модель')),
            ],
        ),
        migrations.CreateModel(
            name='CarImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='cars/')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='item.car')),
            ],
            options={
                'verbose_name': 'Превью фото',
                'verbose_name_plural': 'Превью фото',
            },
        ),
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rent_start', models.DateField(verbose_name='Дата начала аренды')),
                ('rent_end', models.DateField(verbose_name='Дата окончания аренды')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rents', to='item.car', verbose_name='Авто')),
            ],
            options={
                'verbose_name': 'Аренда',
                'verbose_name_plural': 'Аренды',
            },
        ),
    ]
